/**
 * Image registry.
 *
 * Every photograph on the site is referenced through this file. To swap a
 * placeholder for a real photo, drop your file into `public/images/` with the
 * SAME filename and a similar aspect ratio, then update the `alt` text here.
 * No component needs to change.
 *
 * The current files are DUMMY images generated by `pnpm placeholders`
 * (see scripts/generate-placeholders.mjs). They are drawn in the site palette
 * so layout and colour read correctly before real photography exists.
 *
 * `alt` should describe what the picture shows. Decorative background imagery
 * uses an empty alt, which is correct — it carries no information a screen
 * reader user needs.
 */

export type SiteImage = {
  src: string;
  width: number;
  height: number;
  alt: string;
};

export const IMAGES = {
  heroSkyline: {
    src: "/images/hero-skyline.jpg",
    width: 2400,
    height: 1350,
    alt: "",
  },
  propertyMarina: {
    src: "/images/property-marina.jpg",
    width: 1400,
    height: 1750,
    alt: "High-rise residential towers overlooking Dubai Marina at dusk",
  },
  propertyVilla: {
    src: "/images/property-villa.jpg",
    width: 1400,
    height: 1750,
    alt: "A low-rise villa community with palms in the late afternoon",
  },
  propertyOffplan: {
    src: "/images/property-offplan.jpg",
    width: 1400,
    height: 1750,
    alt: "Tower cranes over an off-plan development under construction",
  },
  interiorLobby: {
    src: "/images/interior-lobby.jpg",
    width: 1400,
    height: 1750,
    alt: "An arched residential lobby interior lit in warm gold",
  },
  teamOffice: {
    src: "/images/team-office.jpg",
    width: 1800,
    height: 1200,
    alt: "A brokerage sales floor with agents working at desks",
  },
  compliancePermit: {
    src: "/images/compliance-permit.jpg",
    width: 1600,
    height: 1200,
    alt: "Property paperwork with an official permit stamp",
  },
  securityAbstract: {
    src: "/images/security-abstract.jpg",
    width: 1800,
    height: 1200,
    alt: "",
  },
  ctaPanorama: {
    src: "/images/cta-panorama.jpg",
    width: 2400,
    height: 1000,
    alt: "",
  },
} as const satisfies Record<string, SiteImage>;

export type ImageKey = keyof typeof IMAGES;
